name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # 必須
  contents: read    # 必須

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy Lambda
      env:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
        role-session-name: GitHubActionsSession
      run: |
        zip -r function.zip .
        aws lambda update-function-code --function-name YOUR_FUNCTION_NAME --zip-file fileb://function.zip
